"use client";

import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import type { RewardRow, StudentRow } from "@/lib/db";

type StudentWithRewards = StudentRow & { rewards: RewardRow[]; solved7: number; solved14: number; solved30: number; solved90: number; solved180: number; solved365: number };
type SortMode = "name" | "solved" | "seven" | "fourteen" | "thirty" | "threeMonths" | "sixMonths" | "year";
type Group = { id: number; name: string; slug: string; show_gifts: number; studentIds: number[] };

export function TeacherDashboard({ teacherName }: { teacherName: string }) {
  const router = useRouter(); const [students, setStudents] = useState<StudentWithRewards[]>([]); const [groups, setGroups] = useState<Group[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [editing, setEditing] = useState<StudentWithRewards | null>(null); const [giftEditing, setGiftEditing] = useState<StudentWithRewards | null>(null); const [sortMode, setSortMode] = useState<SortMode>("name");
  async function load() { const [studentResponse, groupResponse] = await Promise.all([fetch("/api/students"), fetch("/api/groups")]); if (studentResponse.status === 401) return router.push("/login"); const [studentData, groupData] = await Promise.all([studentResponse.json(), groupResponse.json()]); setStudents(studentData.students ?? []); setGroups(groupData.groups ?? []); setLoading(false); }
  useEffect(() => { void load(); }, []);
  async function add(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setError(""); const form = event.currentTarget; const values = Object.fromEntries(new FormData(form)); try { const response = await fetch("/api/students", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(values) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setStudents((current) => [...current, data.student].sort((a, b) => `${a.surname}${a.name}`.localeCompare(`${b.surname}${b.name}`))); form.reset(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not add student."); } finally { setSaving(false); } }
  async function remove(student: StudentWithRewards) { if (!confirm(`Delete ${student.acmp_name ?? student.name} from your list?`)) return; const response = await fetch(`/api/students/${student.id}`, { method: "DELETE" }); if (response.ok) setStudents((current) => current.filter((item) => item.id !== student.id)); }
  async function refreshStudent(id: number) { const response = await fetch(`/api/students/${id}`, { method: "PATCH" }); const data = await response.json(); if (response.ok) setStudents((current) => current.map((item) => item.id === id ? data.student : item)); else setError(data.error); }
  async function saveStudentName(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!editing) return; const values = Object.fromEntries(new FormData(event.currentTarget)); const response = await fetch(`/api/students/${editing.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(values) }); const data = await response.json(); if (response.ok) { setStudents((current) => current.map((item) => item.id === editing.id ? data.student : item)); setEditing(null); } else setError(data.error); }
  async function logout() { await fetch("/api/auth/logout", { method: "POST" }); router.push("/"); router.refresh(); }
  function updateRewards(studentId: number, rewards: RewardRow[]) { setStudents((current) => current.map((student) => student.id === studentId ? { ...student, rewards } : student)); setGiftEditing((current) => current?.id === studentId ? { ...current, rewards } : current); }
  async function createGroup(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const name = String(new FormData(form).get("groupName") ?? ""); const response = await fetch("/api/groups", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name }) }); const data = await response.json(); if (response.ok) { setGroups(data.groups); form.reset(); } else setError(data.error); }
  async function updateGroup(group: Group, changes: { showGifts?: boolean; studentIds?: number[] }) { const response = await fetch(`/api/groups/${group.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(changes) }); const data = await response.json(); if (!response.ok) return setError(data.error); setGroups((current) => current.map((item) => item.id === group.id ? { ...item, ...(changes.showGifts === undefined ? {} : { show_gifts: changes.showGifts ? 1 : 0 }), ...(changes.studentIds ? { studentIds: changes.studentIds } : {}) } : item)); }
  async function deleteGroup(group: Group) { if (!confirm(`Delete group ${group.name}?`)) return; const response = await fetch(`/api/groups/${group.id}`, { method: "DELETE" }); if (response.ok) setGroups((current) => current.filter((item) => item.id !== group.id)); }
  const totalSolved = students.reduce((sum, student) => sum + student.solved_count, 0);
  const sortedStudents = [...students].sort((a, b) => { const recentKey: Partial<Record<SortMode, keyof StudentWithRewards>> = { seven: "solved7", fourteen: "solved14", thirty: "solved30", threeMonths: "solved90", sixMonths: "solved180", year: "solved365" }; if (sortMode === "solved") return b.solved_count - a.solved_count; const key = recentKey[sortMode]; if (key) return Number(b[key]) - Number(a[key]) || b.solved_count - a.solved_count; return `${a.name} ${a.surname}`.localeCompare(`${b.name} ${b.surname}`, undefined, { sensitivity: "base" }); });
  return <main className="teacher-shell">
    <nav className="teacher-nav"><a className="brand" href="/"><span>A</span><b>ACMP Visualizer</b></a><div><a href="/ranklists/manage">Ranklists</a><span>{teacherName}</span><button onClick={logout}>Log out</button></div></nav>
    <section className="teacher-content"><header className="dashboard-heading"><div><span className="eyebrow">TEACHER DASHBOARD</span><h1>Your students</h1><p>Save ACMP profiles and monitor their latest progress.</p></div><div className="class-summary"><span><b>{students.length}</b>Students</span><span><b>{totalSolved.toLocaleString()}</b>Total solves</span></div></header>
      <article className="add-student card"><h2>Add a student</h2><p className="add-hint">Enter only the ACMP ID. The profile name and statistics will be loaded automatically.</p><form onSubmit={add}><label>ACMP user ID<input name="acmpId" required inputMode="numeric" placeholder="470224" /></label><button disabled={saving}>{saving ? "Checking ACMP…" : "Add student"}</button></form>{error && <div className="auth-error">{error}</div>}</article>
      <article className="groups-card card"><header><div><span className="eyebrow">SHAREABLE STANDINGS</span><h2>Your groups</h2><p>Create a group, select students, and share its public live standings.</p></div><form onSubmit={createGroup}><input name="groupName" required maxLength={80} placeholder="Group name" /><button>Create group</button></form></header>{groups.length === 0 ? <div className="group-empty">No groups yet.</div> : <div className="group-list">{groups.map((group) => <article key={group.id}><header><div><h3>{group.name}</h3><span>{group.studentIds.length} students</span></div><div><a href={`/standings/${group.slug}`} target="_blank" rel="noreferrer">Open standings ↗</a><button onClick={() => navigator.clipboard.writeText(`${window.location.origin}/standings/${group.slug}`)}>Copy link</button><button className="delete" onClick={() => deleteGroup(group)}>×</button></div></header><div className="group-options"><label className="gift-toggle"><input type="checkbox" checked={Boolean(group.show_gifts)} onChange={(event) => updateGroup(group, { showGifts: event.target.checked })} /><span>Show delivered gift checkpoints publicly</span></label><GroupMemberPicker group={group} students={students} onSave={(studentIds) => updateGroup(group, { studentIds })} /></div></article>)}</div>}</article>
      <article className="roster card"><header><div><h2>Student reward tracks</h2><p>Progress updates from solved totals. Mark a gift only after you give it.</p></div><div className="roster-tools"><label>Sort students<select value={sortMode} onChange={(event) => setSortMode(event.target.value as SortMode)}><option value="name">Name A–Z</option><option value="solved">Total solved</option><option value="seven">Solved · last 7 days</option><option value="fourteen">Solved · last 14 days</option><option value="thirty">Solved · last 30 days</option><option value="threeMonths">Solved · last 3 months</option><option value="sixMonths">Solved · last 6 months</option><option value="year">Solved · last 1 year</option></select></label><b>{students.length}</b></div></header>{loading ? <div className="roster-empty">Loading students and recent activity…</div> : students.length === 0 ? <div className="roster-empty">No students yet. Add the first ACMP profile above.</div> : <div className="student-list"><div className="student-head"><span>Student</span><span>ACMP ID</span><span>Solved</span><span>Unsolved</span><span>Last synced</span><span>Actions</span></div>{sortedStudents.map((student) => { const displayName = [student.name, student.surname].filter(Boolean).join(" ") || student.acmp_name || `ACMP ${student.acmp_id}`; return <section className="student-card-row" key={student.id}><div className="student-row"><a className="student-name" href={`/student/${student.id}`} target="_blank" rel="noreferrer"><span>{displayName.slice(0, 2).toUpperCase()}</span><p><b>{displayName}</b><small>{student.acmp_name ?? "ACMP public profile"}</small></p></a><a href={`/student/${student.id}`} target="_blank" rel="noreferrer">#{student.acmp_id} ↗</a><b className="solved-number">{student.solved_count}</b><b className="unsolved-number">{student.unsolved_count}</b><small>{student.last_synced ? new Date(student.last_synced).toLocaleDateString() : "—"}</small><div className="student-actions"><button className="gift-action" onClick={() => setGiftEditing(student)} title="Edit gifts">🎁</button><button onClick={() => setEditing(student)} title="Edit student name">✎</button><button onClick={() => refreshStudent(student.id)} title="Refresh profile">↻</button><button className="delete" onClick={() => remove(student)} title="Delete student">×</button></div></div><RewardProgress student={student} onEdit={() => setGiftEditing(student)} /></section>; })}</div>}</article>
      {editing && <div className="edit-overlay" onMouseDown={() => setEditing(null)}><section className="edit-dialog" onMouseDown={(event) => event.stopPropagation()}><header><div><span className="eyebrow">EDIT STUDENT</span><h2>Change student name</h2></div><button onClick={() => setEditing(null)}>×</button></header><p>ACMP ID #{editing.acmp_id} · Public profile: {editing.acmp_name}</p><form onSubmit={saveStudentName}><label>Name<input name="name" required defaultValue={editing.name} autoFocus /></label><label>Surname<input name="surname" required defaultValue={editing.surname} /></label><div><button type="button" onClick={() => setEditing(null)}>Cancel</button><button type="submit">Save changes</button></div></form></section></div>}
      {giftEditing && <GiftManager student={giftEditing} onClose={() => setGiftEditing(null)} onUpdate={(rewards) => updateRewards(giftEditing.id, rewards)} />}
    </section>
  </main>;
}

function RewardProgress({ student, onEdit }: { student: StudentWithRewards; onEdit: () => void }) {
  const rewards = [...student.rewards].sort((a, b) => a.target_solved - b.target_solved); const next = rewards.find((reward) => !reward.delivered && reward.target_solved > student.solved_count) ?? rewards.find((reward) => !reward.delivered); const maximum = Math.max(next?.target_solved ?? student.solved_count, rewards.at(-1)?.target_solved ?? 1); const progress = Math.min(100, student.solved_count / maximum * 100);
  return <div className="reward-progress"><div className="reward-track"><i style={{ width: `${progress}%` }} />{rewards.map((reward) => <button key={reward.id} type="button" className={`${reward.delivered ? "delivered" : ""} ${student.solved_count >= reward.target_solved ? "reached" : ""}`} style={{ left: `${Math.min(100, reward.target_solved / maximum * 100)}%` }} onClick={onEdit} title={`${reward.gift_name} at ${reward.target_solved} solved${reward.delivered ? " · delivered" : ""}`}>{reward.image_data ? <img src={reward.image_data} alt={reward.gift_name} /> : <span>🎁</span>}<b>{reward.target_solved}</b></button>)}</div><div className="reward-caption"><b>{student.solved_count} problems solved</b><div className="recent-solves"><span><b>+{student.solved7}</b> last 7 days</span><span><b>+{student.solved14}</b> 14d</span><span><b>+{student.solved30}</b> 30d</span><span><b>+{student.solved90}</b> 3mo</span><span><b>+{student.solved180}</b> 6mo</span><span><b>+{student.solved365}</b> 1y</span></div><span>{next ? `${Math.max(0, next.target_solved - student.solved_count)} problems left to ${next.gift_name}` : rewards.length ? "All gifts delivered!" : "No gifts yet"}</span></div></div>;
}

function GiftManager({ student, onClose, onUpdate }: { student: StudentWithRewards; onClose: () => void; onUpdate: (rewards: RewardRow[]) => void }) {
  const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  async function addReward(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setError(""); const form = event.currentTarget; const formData = new FormData(form); const file = formData.get("photo") as File; let imageData = ""; if (file?.size) { if (file.size > 2_000_000) { setError("Gift photo must be smaller than 2 MB."); setSaving(false); return; } imageData = await new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = () => reject(new Error("Could not read the image.")); reader.readAsDataURL(file); }); } const response = await fetch(`/api/students/${student.id}/rewards`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ targetSolved: Number(formData.get("targetSolved")), giftName: formData.get("giftName"), imageData }) }); const data = await response.json(); if (response.ok) { onUpdate(data.rewards); form.reset(); } else setError(data.error); setSaving(false); }
  async function checkpoint(reward: RewardRow) { const response = await fetch(`/api/students/${student.id}/rewards`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ rewardId: reward.id, delivered: !reward.delivered }) }); const data = await response.json(); if (response.ok) onUpdate(data.rewards); else setError(data.error); }
  async function removeReward(reward: RewardRow) { if (!confirm(`Delete the ${reward.gift_name} goal?`)) return; const response = await fetch(`/api/students/${student.id}/rewards?rewardId=${reward.id}`, { method: "DELETE" }); const data = await response.json(); if (response.ok) onUpdate(data.rewards); else setError(data.error); }
  return <div className="edit-overlay" onMouseDown={onClose}><section className="edit-dialog gift-dialog" onMouseDown={(event) => event.stopPropagation()}><header><div><span className="eyebrow">REWARD PLAN</span><h2>{student.name}&apos;s gifts</h2></div><button onClick={onClose}>×</button></header><p>Create personal solved-problem goals. Check “Delivered” only after the student receives the gift.</p><form className="gift-form" onSubmit={addReward}><div className="gift-fields"><label>Solved target<input name="targetSolved" type="number" min="1" required placeholder="100" /></label><label>Gift name<input name="giftName" required maxLength={80} placeholder="Cup" /></label></div><label>Gift photo<input name="photo" type="file" accept="image/png,image/jpeg,image/webp,image/gif" /></label>{error && <div className="auth-error">{error}</div>}<button type="submit" disabled={saving}>{saving ? "Saving…" : "+ Add gift milestone"}</button></form><div className="gift-list">{student.rewards.length === 0 ? <div className="gift-empty">No gift milestones yet.</div> : [...student.rewards].sort((a, b) => a.target_solved - b.target_solved).map((reward) => <article className={reward.delivered ? "delivered" : ""} key={reward.id}>{reward.image_data ? <img src={reward.image_data} alt={reward.gift_name} /> : <span>🎁</span>}<div><b>{reward.gift_name}</b><small>{reward.target_solved} solved problems</small></div><label><input type="checkbox" checked={Boolean(reward.delivered)} onChange={() => checkpoint(reward)} /> Delivered</label><button onClick={() => removeReward(reward)} title="Delete gift">×</button></article>)}</div></section></div>;
}

function GroupMemberPicker({ group, students, onSave }: { group: Group; students: StudentWithRewards[]; onSave: (studentIds: number[]) => Promise<void> }) {
  const [selected, setSelected] = useState(group.studentIds); const [saving, setSaving] = useState(false); const [saved, setSaved] = useState(false);
  function toggle(studentId: number) { setSaved(false); setSelected((current) => current.includes(studentId) ? current.filter((id) => id !== studentId) : [...current, studentId]); }
  async function save() { setSaving(true); await onSave(selected); setSaving(false); setSaved(true); }
  return <details><summary>Choose group students <b>{selected.length}</b></summary><div>{students.map((student) => <label key={student.id}><input type="checkbox" checked={selected.includes(student.id)} onChange={() => toggle(student.id)} /><span>{[student.name, student.surname].filter(Boolean).join(" ")}</span><b>{student.solved_count} solved</b></label>)}</div><footer><button type="button" onClick={save} disabled={saving}>{saving ? "Saving…" : saved ? "✓ Saved" : "Save students"}</button></footer></details>;
}



